=== forcedotcom/analyticsdx-vscode/extensions/analyticsdx-vscode-templates/schemas/folder-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://schemas.salesforce.com/analytics/templates/folder.json",
  "title": "Salesforce Analytics Template Folder Definition",
  "description": "",
  "type": "object",
  "additionalProperties": false,
  "allowComments": true,
  "required": [],
  "properties": {
    "name": {
      "$comment": "A lot of these fields are valid to be literal null, and there are existing files that do that already",
      "type": ["string", "null"]
    },
    "label": {
      "type": ["string", "null"]
    },
    "description": {
      "type": ["string", "null"]
    },
    "featuredAssets": {
      "type": "object",
      "description": "Determines the dashboards to feature, and the order in which to list them, in an app created from the template. If empty, app features all dashboards listed in alphabetical order according to label.",
      "required": [],
      "additionalProperties": false,
      "properties": {
        "default": {
          "type": "object",
          "required": [],
          "additionalProperties": false,
          "properties": {
            "assets": {
              "type": "array",
              "description": "List of dashboards to feature in the created app, in the order in which to list them.",
              "minItems": 0,
              "items": {
                "type": "object",
                "required": ["id"],
                "additionalProperties": false,
                "$comment": "Most just include id, but Learning Adventure also has these",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "The id for the dashboard to feature. Use the the format ${App.Dashboards['Sales Analytics Home'].Id}."
                  },
                  "name": {
                    "type": ["string", "null"]
                  },
                  "namespace": {
                    "type": ["string", "null"]
                  },
                  "type": {
                    "type": ["string", "null"]
                  }
                },
                "defaultSnippets": [
                  {
                    "label": "New featuredAsset",
                    "body": {
                      "id": "${1:id}"
                    }
                  }
                ]
              }
            }
          },
          "defaultSnippets": [
            {
              "label": "New featuresAssets",
              "body": {
                "assets": []
              }
            }
          ]
        }
      },
      "defaultSnippets": [
        {
          "label": "New featuredAssets",
          "body": {
            "default": {
              "assets": []
            }
          }
        }
      ]
    },
    "shares": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "required": ["accessType", "shareType"],
        "additionalProperties": false,
        "properties": {
          "accessType": {
            "type": "string",
            "enum": ["View", "Edit", "Manage"],
            "default": "View"
          },
          "shareType": {
            "type": "string",
            "enum": [
              "Group",
              "Organization",
              "Role",
              "RoleAndSubordinates",
              "User",
              "PortalRole",
              "PortalRoleAndSubordinates",
              "AllCspUsers",
              "AllPrmUsers",
              "PartnerUser",
              "CustomerPortalUser"
            ],
            "default": "Organization"
          },
          "sharedWithId": {
            "type": ["string", "null"]
          }
        },
        "defaultSnippets": [
          {
            "label": "New share",
            "body": {
              "accessType": "${1:View}",
              "shareType": "${2:Organization}"
            }
          }
        ]
      }
    }
  }
}

=== forcedotcom/analyticsdx-vscode/packages/analyticsdx-template-lint/test/unit/schemas/testfiles/folder/valid/all-fields.json
{
  "name": "AllFields",
  "label": "AllFields",
  "description": "Test all the available fields and values for folder.json",
  "featuredAssets": {
    "default": {
      "assets": [
        {
          "id": "assetId",
          "name": "assetName",
          "namespace": "assetNamespace",
          "type": "assetType"
        }
      ]
    }
  },
  "shares": [
    {
      "accessType": "View",
      "shareType": "Organization",
      "sharedWithId": "someId"
    },
    {
      "accessType": "Edit",
      "shareType": "Organization"
    },
    {
      "accessType": "Manage",
      "shareType": "Organization"
    },
    {
      "accessType": "View",
      "shareType": "AllCspUsers"
    },
    {
      "accessType": "View",
      "shareType": "AllPrmUsers"
    },
    {
      "accessType": "View",
      "shareType": "CustomerPortalUser"
    },
    {
      "accessType": "View",
      "shareType": "Group"
    },
    {
      "accessType": "View",
      "shareType": "PartnerUser"
    },
    {
      "accessType": "View",
      "shareType": "PortalRole"
    },
    {
      "accessType": "View",
      "shareType": "PortalRoleAndSubordinates"
    },
    {
      "accessType": "View",
      "shareType": "Role"
    },
    {
      "accessType": "View",
      "shareType": "RoleAndSubordinates"
    },
    {
      "accessType": "View",
      "shareType": "User"
    }
  ]
}

=== forcedotcom/analyticsdx-vscode/extensions/analyticsdx-vscode-templates/test/unit/schema/testfiles/folder/valid/with-nulls.json
{
  "name": null,
  "label": null,
  "description": null,
  "featuredAssets": {
    "default": {
      "assets": [
        {
          "id": "${App.Dashboards['Adventure Home'].Id}",
          "name": null,
          "namespace": "${Org.Namespace}",
          "type": null
        }
      ]
    }
  },
  "shares": [
    {
      "accessType": "Edit",
      "shareType": "AllCspUsers",
      "sharedWithId": null
    }
  ]
}
